/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-stroke": "#27272A",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#474646",
        "tertiary-container": "#1a0500",
        "on-secondary": "#2f3131",
        "on-tertiary": "#571f00",
        "surface-dim": "#131313",
        "secondary-container": "#454747",
        "surface-variant": "#353534",
        "inverse-primary": "#5f5e5e",
        "pure-white": "#FFFFFF",
        "on-tertiary-container": "#cb5610",
        "racing-orange": "#E26723",
        surface: "#131313",
        "on-secondary-container": "#b4b5b5",
        "on-primary": "#313030",
        "surface-bright": "#393939",
        background: "#131313",
        "primary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#c6c6c7",
        "on-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "primary-container": "#0b0b0b",
        "on-error": "#690005",
        "outline-variant": "#444748",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#454747",
        primary: "#c9c6c5",
        "on-tertiary-fixed": "#351000",
        "surface-container-highest": "#353534",
        "tertiary-fixed-dim": "#ffb694",
        outline: "#8e9192",
        tertiary: "#ffb694",
        "surface-container": "#201f1f",
        "asphalt-gray": "#71717A",
        "on-primary-container": "#7b7979",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed": "#ffdbcc",
        "surface-charcoal": "#1C1C1E",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#1c1b1b",
        secondary: "#c6c6c7",
        "surface-tint": "#c9c6c5",
        "crimson-heat": "#FF2A2A",
        "on-surface-variant": "#c4c7c7",
        "secondary-fixed": "#e2e2e2"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-lg": "1.5rem",
        "margin-lg": "3.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin-md": "2rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        margin: "1rem"
      },
      fontFamily: {
        "display-hero": ["Oswald", "sans-serif"],
        "headline-xl-mobile": ["Oswald", "sans-serif"],
        "display-hero-mobile": ["Oswald", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Oswald", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Oswald", "sans-serif"],
        "label-mono": ["Space Grotesk", "monospace"],
        "headline-lg": ["Oswald", "sans-serif"]
      },
      fontSize: {
        "display-hero": ["80px", { lineHeight: "84px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "36px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "26px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["13px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
